callapp/urls.py
from callapp.tokens import Accountactivate
from callapp.views import Homepage
from django.urls import path
from .views import  register, user_login, Accountactivate, edit,contact, call_logs,call_delete,see_feedback
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from . import views

app_name = 'callapp'

urlpatterns =[
    path('', Homepage.as_view(), name="home"),
    path('register/', register, name="register"),
    path('login/', user_login, name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('activate/<uidb64>/<token>/', Accountactivate.as_view(), name='activate'),
    path('edit/', edit, name="edit"),
    path('schedule/',contact, name="schedule"),
    path('password_change/',auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('callapp:password_change_done')),name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    path('calls', call_logs, name='home'),
    path('<pk>/delete/',call_delete.as_view(), name = "delete"),
    path('<pk>/feedback/',see_feedback.as_view(), name = "feed")

]

callpal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = "callapp"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('callapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

callapp/models.py
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User

Bookingchoice =(
    ("Marital/Relationship", "Marital/Relationship"),
    ("Birthday wishes/greetings", "Birthday wishes/greetings"),
    ("Counselling/motivation", "Counselling/motivation"),
    ("Business tips/ideas", "Business tips/ideas"),
    ("Call a friend", "Call a friend"),
    ("Other", "Other"),
)

approval_choice =(
    ("Pending", "Pending"),
    ("Approved","Approved"),
    ("Denied","Denied")
)

class profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    country = models.CharField(max_length=200)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/',blank=True)

    def __str__(self):
        return f'Profile for user {self.user.username}'

class book(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, null = True)
    name = models.CharField(max_length=250,null=True)
    email = models.EmailField()
    subject = models.CharField(max_length=250)
    specify = models.CharField(max_length=250)
    message = models.TextField()
    identification = models.IntegerField(null=True)
    schedule = models.CharField(max_length=250)
    send_dt = models.DateTimeField(null=True)     
    status = models.CharField( choices=approval_choice, max_length=250, default="Pending")
    date_posted = models.DateTimeField(auto_now_add=True, null=True)
    feedback = models.TextField(null=True)

# class blog(models.Model):
#     author = models.ForeignKey(User,on_delete=models.CASCADE)
#     topic = models.CharField(max_length=250)
#     image = models.ImageField()
#     description = models.TextField()
#     like = models.ManyToManyField()
    
# class account(models.Model):
#     owner= models.ForeignKey(User, on_delete=models.CASCADE, related_name="top")
#     account_balance = models.DecimalField(max_digits=10,decimal_places=2)
#     date_created = models.DateField(auto_now_add=True)
#     account_number = models.CharField(max_length=50)


# class transfer(models.Model):
#     owner = models.ForeignKey(User,on_delete=models.CASCADE, blank=True, null=True)
#     from_account = models.CharField(max_length=50)
#     to_account = models.CharField(max_length=50)
#     amount = models.CharField(max_length=50)
#     date_created = models.DateField(auto_now_add=True)

#     def __str__(self):
#         return str(self.amount)
        
    





# @receiver(post_save, sender=User)
# def update_user_profile(sender,instance, created, **kwargs):
#     if created:
#         profile.objects.create(user=instance)
#         instance.profile.save()

# @receiver(post_save, sender=User) #add this
# def create_user_profile(sender, instance, created, **kwargs):
# 	if created:
# 		profile.objects.create(user=instance)

# @receiver(post_save, sender=User) #add this
# def save_user_profile(sender, instance, **kwargs):
# 	instance.profile.save()

callapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import models
from django.db.models.query import QuerySet
from django.forms import fields
from django.forms.models import ModelForm
from .models import profile, book



Bookingchoice =(
    ("Marital/Relationship", "Marital/Relationship"),
    ("Birthday wishes/greetings", "Birthday wishes/greetings"),
    ("Counselling/motivation", "Counselling/motivation"),
    ("Business tips/ideas", "Business tips/ideas"),
    ("Call a friend", "Call a friend"),
    ("Other", "Other"),
)


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Username",                
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",                
                "class": "form-control"
            }
        ))

class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Username",                
                "class": "form-control"
            }
        ))
        
    fullname = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "fullname",                
                "class": "form-control"
            }
        ))
    phone = forms.CharField(
        widget=forms.NumberInput(
            attrs={
                "placeholder" : "phone",                
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder" : "Email",                
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",                
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password check",                
                "class": "form-control"
            }
        ))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2','phone','fullname')



class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')
class ProfileEditForm(forms.ModelForm):

    date_of_birth = forms.DateField(
        widget=forms.DateInput(
            attrs={
                "placeholder" : "date of birth",                
                "class": "form-control"
            }
        )), 

    class Meta:
        model = profile
        fields = ('country','date_of_birth','photo')

class BookForm(forms.ModelForm):
   
    # name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "placeholder" : "Name",                
    #             "class": "form-control"
    #         }
    #     )) 
    # email = forms.EmailField(
    #     widget=forms.EmailInput(
    #         attrs={
    #             "placeholder" : "Email",                
    #             "class": "form-control"
    #         }
    #     )) 

    subject = forms.ChoiceField(choices= Bookingchoice,required=False,
        widget=forms.Select(
            attrs={
                "placeholder" : "Subject",                
                "class": "form-control"
            }
        ))
    specify = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "specify",                
                "class": "form-control subject_specify",
                
            }
        ),required = False)
    # message = forms.CharField(
    #     widget=forms.Textarea(
    #         attrs={
    #             "placeholder" : "Message",                
    #             "class": "form-control"
    #         }
    #     ))
    
    NOW, LATER = 'now', 'later'
    SCHEDULE_CHOICES = (
        (NOW, 'Send immediately'),
        (LATER, 'Send later'),
    )
    schedule = forms.ChoiceField(choices=SCHEDULE_CHOICES, widget=forms.RadioSelect(
            attrs={
                "placeholder" : "schedule call",                 
                "class": "form-control"
            }
        ))
        
        
    send_dt = forms.DateField(label="", required=False)


    def __init__(self, data=None, *args, **kwargs):
        super().__init__(data, *args, **kwargs)

        # If 'later' is chosen, mark send_dt as required.
        if data and data.get('schedule', None) == self.LATER:
            self.fields['send_dt'].required = True

    class Meta:
        model = book
        fields = ('name','email', 'subject', 'specify','message','identification','schedule','send_dt')

callapp/views.py
import decimal
from django.contrib.auth import authenticate, backends,login, tokens, views
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.messages.api import success
from django.db.models.query_utils import Q
from django.dispatch.dispatcher import receiver
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.core.mail import EmailMessage
from django.views.generic import TemplateView,View, DeleteView,DetailView
from .models import book, profile
from .forms import LoginForm, SignUpForm,ProfileEditForm,UserEditForm,BookForm
from django.urls import reverse_lazy, reverse
from django.contrib.sites.shortcuts import get_current_site
from  django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.template.loader import render_to_string
from .tokens import accountactivation
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, request
from django.utils import timezone
from .models import User
# import shortuuid

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# Create your views here.

class Homepage(TemplateView):
    template_name= "home/home.html"

def user_login(request):
    prime = LoginForm(request.POST or None)
    msg = None
    if request.method == "POST":

        if prime.is_valid():
            username = prime.cleaned_data.get("username")
            password = prime.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_staff:
                    login(request, user)
                    return redirect(reverse_lazy('calls'))
                else:
                    login(request, user)
                    return redirect("/")
            else:    
                msg = 'Invalid credentials'    
        else:
            msg = 'Error validating the prime'    

    return render(request, "registration/login.html", {"prime": prime, "msg" : msg})

def register(request):
    msg     = None
    success = False

    if request.method == "POST":
        prime = SignUpForm(request.POST)
        
        
        if prime.is_valid():
           
            user = prime.save(commit= False)
        
            user.is_active = False
            # user_id = shortuuid.ShortUUID(alphabet ="0123456789")
            # user_rand = user_id.random(length= 5)

            # user = prime.objects.create(field_name = user_rand)
            
            user.save()
            
         
            
            profile.objects.create(user=user)
            current_site = get_current_site(request)

            subject = "activate your account to proceed"
            message = render_to_string('emails/account_activation_email.html',{
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': accountactivation.make_token(user),
            })
            to_email = prime.cleaned_data.get('email')
            email = EmailMessage(subject,message, to = [to_email])
            email.send('please confirm your email to complete registration')

            msg     = 'User created - please go to your email to confirm to enable login <a href="/login">login</a>.'
            success = True
        else:
            msg = 'prime is invalid'
        
    else:
        prime = SignUpForm()
    return render(request, "registration/register.html", {"prime": prime,'msg':msg, 'success':success})



class Accountactivate(View):
    def get(self, request, uidb64, token, *args, **kwargs):

        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and accountactivation.check_token(user,token):
            user.is_active = True
            user.save()
            login(request,user)
            messages.success(request, 'your account has been confirmed')
            return redirect('/')
        else:
            messages.warning(request,'the confirmation link is invalid, possibly it has been used')
        return redirect('/')

@login_required
def edit(request):
    if request.method == 'POST':
        user_prime = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_prime = ProfileEditForm(
                                    instance=request.user.profile,
                                    data=request.POST,
                                    files=request.FILES)
                                    
        if user_prime.is_valid() and profile_prime.is_valid():
            user_prime.save()
            profile_prime.save()
            messages.success(request, 'Profile updated successfully')
            return redirect('/')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_prime = UserEditForm(instance= request.user)
        profile_prime = ProfileEditForm(instance= request.user.profile)

    return render(request,'registration/edit.html',{'user_prime': user_prime,'profile_prime': profile_prime})


@login_required
def contact(request):
    success = False
    if request.method == 'POST':
        prime = BookForm(data=request.POST)
        if prime.is_valid():
            
            prime.save(commit=False)
            
            user_email = prime.cleaned_data['email']
            subject = prime.cleaned_data['subject']
            if prime.cleaned_data['subject'] == "Other":
                prime.subject = request.POST.get('specify')
            
            pindetails = prime.cleaned_data['identification']
            # cc_myself = prime.cleaned_data['cc_myself']
            
            reciptents = 'admin@example.com'

            send_dt = prime.cleaned_data['send_dt']
            if send_dt is None:
                send_dt = "Immediately"
            else: 
                send_dt = prime.cleaned_data['send_dt']
            
            text = f'hello {request.user.username} booked a call with number: {pindetails}, your scheduled date is {send_dt} and {subject} is the topic'
            
            prime.instance.user = request.user
            prime.save()
            # texts= f'hello {name} you have sucessfully booked a call with number: {pindetails}, and {subject} is your topic..An agent will connect {send_dt}'
            # message_2 = (subject, texts,user_email,['admin@example.com'] )
            
            try:
                send_mail(subject,text,user_email,[reciptents])
                success = True
            except BadHeaderError:
                return HttpResponse('Invalid header found')
    else: 
        prime = BookForm()
    return render(request, 'home/schedule.html', {'prime': prime,'success':success})

def call_logs(request):
    

    calls = book.objects.filter(user= request.user)
    print(calls)
    return render(request,'home/call_logs.html',{
        'calls':calls
    })

class call_delete(DeleteView):
    model = book
    success_url = "/"
    template_name = "home/delete_view.html"

class see_feedback(DetailView):
    model = book
    context_object_name ="feeds"
    template_name = "feed_view.html"

callapp/templates/home/call_logs.html
{% extends "base.html" %}
{% block title %} Call logs{% endblock title %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    {% block content %}

        <p>welcome </p>
        <table>
            <tr>
                <th>Identification</th>
                <th>Message</th>
                <th>Subject</th>
                <th>Status</th>
                <th>Feedback</th>
                <th>account balance</th>
            </tr>{% for call in calls %}
            
            <tr>        
                <td>{{call.identification}}</td>
                <td>{{call.message}}</td>
                <td>{{call.subject}}</td>
                <td>{{call.status}}</td>
                <td><a href = "{% url 'callapp:feed' pk=call.id %}"role="button">Feedback</a></td>
                <td><a href = "{% url 'callapp:delete' pk=call.id %}"role="button">Delete</a></td>

                <td>{{account_balance}}</td>
            </tr>{%endfor %}
        </table>
       
       
    {% endblock content %}

   
</body>

</html>

callapp/templates/home/delete_view.html
<html>

<head>
    <title>delete</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p> Are you sure you want delete this request?</p>
        <input type="submit" value="Confirm">
    </form>
</body>
</html>

callapp/templates/home/home.html
{% extends "base.html" %}
{% block title %} Home{% endblock title %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    {% block content %}

        <p>welcome to our platform, we are here to for you!</p> <br>

       <p>balancen {{ balance.account_balance }}</p>
        
        {% if messages %}
            <ul id="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags}}"{% endif %}>{{message}}</li>
                {% endfor %}
            </ul>

        {% endif %}
        <script>
            setTimeout(function(){
                document.getElementById('messages').style.display = 'none';
            },1000);
         </script>
    {% endblock content %}

</body>

</html>

callapp/templates/home/payment.html
{% extends "base.html" %}
{% block title %} Payment{% endblock title %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    {% block content %}

       
        <p>
            <h2 style="color: white">payment</h2>
        </p>
        <!-- <form method="post" action="">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-large">Send Message</button>
        </form>
        <p>
            <h2 style="color: white">SCHEDULE FORM</h2>
        </p> -->
        Hello {{request.user.username}} !! <br><br>
        Balance: {{balance}}
        {% if msg%}
            <br><br>
            {{msg}}
        {% endif %}
        
        <br><br>
        
        <form method="post">
                <input type="text" name="username" placeholder="Enter Username">
                <input type="text" name="amount" placeholder="Enter Amount">
                <input type="submit" value="Submit">
                {% csrf_token %}
        </form>
        <br><br>
        
       
       
    {% endblock content %}

   
</body>

</html>

callapp/templates/home/schedule.html
{% extends "base.html" %}
{% block title %} Schedule{% endblock title %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    
    
    
    <script src='main.js'></script>
    
</head>
<body onload="hide_user()">
    {% block content %}

        <p>Book a call with us </p>
        {% if success %}
            <p>Call booked successfully, <a href="{% url "callapp:calls" %}"  >click to see scheduled calls</a></p>
            <script>
                setTimeout("window.location.href=/;", 5000);
                
            </script>
             
              
        {% else %}
        <p>
            <h2 style="color:blue">SCHEDULE FORM</h2>
        </p>
        
        <!-- <style>
            #id_user{
            display:none;
            }
        </style> -->
       <form method="post" action="" novalidate>
            {% csrf_token %}
           <input disabled type = "text" value={{request.user.username}} style="margin-left:-5opx;">
            {{prime.as_p}}
            

        <button type="submit" class="btn btn-large">Send Message</button>
        </form>
    
        {% endif %}
    
    {% endblock content %}
        

     {% block extrascript %}
     <script>
    //    jQuery('#id_user').hide()
    //    $("[for=id_user]").hide();
   </script>
            <script>
                //  $( document ).ready(function() {
                //     jQuery('#id_specify').hide();
                //     $("[for=id_specify]").hide();
                // });
                jQuery('#id_subject').on('change', () => {
            // You can also do this with document.querySelector('')
            if ($('#id_subject option:selected').text() == 'Other') {
                jQuery('#id_specify').show()
                  $("[for=id_specify]").show()
                        
            } else {                        
                jQuery('#id_specify').hide()
                  $("[for=id_specify]").hide()
                  
                 

            }
        }); 
    </script>
     {% endblock extrascript %}
</body>

</html>